server/database.sql, server/models/auth/forgotPassword.js, server/models/auth/index.js, server/models/auth/resetPassword.js, server/models/auth/signup.js, server/models/auth/updatePassword.js, server/routes/auth/forgotPassword.js, server/routes/auth/index.js, server/routes/auth/resetPassword.js, server/routes/auth/updatePassword.js, server/routes/index.js, server/routes/middlewares/index.js, server/routes/middlewares/verifyUser.js, server/schema/auth/forgotPassword.js, server/schema/auth/index.js, server/schema/auth/resetPassword.js, server/schema/auth/signup.js, server/schema/auth/updatePassword.js
Signed-off-by: ridhishjain <ultimate.ridhish@gmail.com>
=> forgot_password, reset_password, update_password APIs implemented

server/database.sql, server/models/auth/getUser.js, server/models/auth/index.js, server/models/auth/updateUser.js, server/models/auth/verifyNewEmail.js, server/routes/auth/getUser.js, server/routes/auth/index.js, server/routes/auth/updateUser.js, server/routes/auth/verifyNewEmail.js, server/routes/index.js, server/schema/auth/forgotPassword.js, server/schema/auth/index.js, server/schema/auth/updateUser.js, server/schema/auth/verifyNewEmail.js
=> update_user and verify_new_email API implemented

README.md, server/example.env
- Also added a example.env for setting up .env file
=> Update readme to include export SQL file instructions and setting up environment variables

.travis.yml
integration of node -10 -12 -14 || os -windows, osx, mac || arch -amd64
=> node -10 -12 -14 || os -windows, osx, linux || arch -amd64

server/models/auth/forgotPassword.js, server/models/auth/verifyEmail.js
=> Auth APIs bugs resolved

server/database.sql, server/models/auth/getUser.js, server/models/auth/login.js, server/models/auth/signup.js, server/models/auth/updateUser.js, server/schema/auth/signup.js, server/schema/auth/updateUser.js
Signed-off-by: ridhisjain <ultimate.ridhish@gmail.com>
resolves #30
=> Branch, Department and Bio

server/config/cloudinary.js, server/database.sql, server/example.env, server/models/auth/index.js, server/models/auth/uploadProfileImage.js, server/package-lock.json, server/package.json, server/routes/auth/index.js, server/routes/auth/uploadProfileImage.js, server/routes/index.js, server/routes/middlewares/verifyUser.js
Used [Cloudinary](https://cloudinary.com/) to store images. Only the link to image would be stored in DB.
Fixes #26 
Some other minor changes made :
- Included a default error handler for internal server errors.
- Added `nodemon` and a `dev` script in server, which is useful as `nodemon` automatically restarts the node application when file changes are made
- In `verifyUserAccessToken()` middleware, also store the `username` in `request.username`, as when uploading image, the request has no body.
=> Developed the API for uploading user profile image

frontend/components/Signup.js, frontend/shared/CONSTANTS.js, package.json, server/database.sql, server/models/auth/getUser.js, server/models/auth/login.js, server/models/auth/signup.js, server/models/auth/updateUser.js, server/schema/auth/signup.js, server/schema/auth/updateUser.js
Some other changes :
- When user tries to sign up with a username, which is already taken, appropriate error message is returned
- Rename `branch` to `course`
- Remove `mobile` field from signup form
- Reduce expiry time for JWT token to 24 hours, for security reasons
- Added `PhD` as a course
- Modified `lint:fix` script in the main package.json file, for it to work correctly
=> Added admission_year in users table and updated frontend of signup form

server/schema/groups/addBranch.js, server/schema/groups/addMembers.js, server/schema/groups/addModerator.js, server/schema/groups/createGroup.js, server/schema/groups/index.js, server/schema/groups/removeBranch.js, server/schema/groups/removeGroup.js, server/schema/groups/removeMembers.js, server/schema/groups/removeModerator.js, server/schema/groups/updateGroupName.js
**Do not merge, discussion required**
Further addition to #37 
API endpoints:
* **`POST /groups/create_group`** **Admin only**: Frontend would send group_name, confidential and usernames ( a JSON array of usernames to be added in that group ). The array may be empty.
* **`DELETE /groups/remove_group`** **Admin only**: Frontend would send group_id.
* **`POST groups/:group_id/add_branch`** **Moderator only**: receive a branch code and a department code. Users who are having those branch code and department code and not present in the group already, should be added to the group
* **`POST groups/:group_id/remove_branch`** **Moderator only**: receive a branch code and a department code. Users who are having those branch code and department code and not present in the group already, should be …
=> `groups` Schema

frontend/components/auth/Login.js, frontend/components/auth/Signup.js, frontend/components/user/updateUserForm.js, frontend/components/user/uploadProfileImage.js, frontend/components/utils/withPrivateRoute.js, frontend/pages/index.js, frontend/shared/CONSTANTS.js, server/routes/middlewares/verifyUser.js
Fixes #44 
Other minor changes
- Moved signup and login components to `auth` directory
- Add overlay for 'Click here to update profile image' in `edit-profile` component
=> Delete expired JWT Token in frontend and add error message for expired token in server

server/database.sql, server/models/auth/login.js, server/models/user/updatePassword.js, server/models/utils/isPasswordCorrect.js, server/routes/middlewares/index.js, server/routes/middlewares/verifyAdmin.js, server/routes/middlewares/verifyUser.js
Required for #37 
@ridhishjain , kindly review this once.
The verifyAdmin middleware should be used only after the middleware `verifyUserAccessToken`
**Changes made in DB** :
1. Updated DB Tables to include AUTO_INCREMENT on primary key - id 
2. Also include created_at in notifications table by DEFAULT
3. Added foreign key constraint for creator of a group
=> Add middleware for verifyAdmin and update SQL tables from notifications and user_notifications

server/database.sql, server/models/groups/createGroup.js, server/models/groups/index.js, server/models/groups/removeGroup.js, server/routes/groups/createGroup.js, server/routes/groups/index.js, server/routes/groups/removeGroup.js, server/routes/index.js
=> `POST /groups` & `DELETE /groups/:group_id` 

frontend/components/common/AdminNavbar/DesktopView.js, frontend/components/common/AdminNavbar/MobileView.js, frontend/components/common/AdminNavbar/index.js, frontend/components/common/Header.js, frontend/components/common/SearchUsers.js, frontend/components/manage/notifications/createNotificationForm.js, frontend/components/manage/notifications/notificationListItem.js, frontend/components/utils/withAdminRoute.js, frontend/package-lock.json, frontend/package.json, frontend/pages/_app.js, frontend/pages/manage/notifications/create.js, frontend/pages/manage/notifications/index.js, frontend/pages/notifications.js, frontend/utils/timeSince.js, server/models/notifications/getCreatorNotifications.js, server/models/notifications/index.js, server/models/search/index.js, server/models/search/searchUsers.js, server/routes/index.js, server/routes/notifications/getCreatorNotifications.js, server/routes/notifications/index.js, server/routes/search/index.js, server/routes/search/searchUsers.js
Fixes #51 
Server changes :
- Added API for '/search/users'
- Added API for '/notifications/creator_notifications'
=> Frontend for 'create-notification', 'view notifications' and 'manage notifications'

frontend/components/common/AdminNavbar/DesktopView.js, frontend/components/common/AdminNavbar/MobileView.js, frontend/components/common/AdminNavbar/index.js, frontend/components/common/Header.js, frontend/components/manage/groups/groupDetail.js, frontend/components/manage/groups/groupListItem.js, frontend/components/manage/groups/manageMemberDetail.js, frontend/components/manage/groups/manageModeratorDetail.js, frontend/components/manage/groups/memberDetail.js, frontend/pages/groups/[group_id].js, frontend/pages/groups/index.js, frontend/pages/manage/groups/index.js, server/routes/groups/removeModerator.js
=> Frontend for view groups

package.json
Install a fresh set of dependencies in all directories
Now just run `npm run dep:install`
=> add: script to install fresh set of dependencies

server/database.sql, server/schema/questions/createQuestion.js, server/schema/questions/index.js, server/schema/questions/updateQuestion.js
=> create: schema validation for createQuestion and updateQuestion

server/schema/submissions/createSubmission.js, server/schema/submissions/index.js, server/schema/tags/createTag.js, server/schema/tags/index.js
=> Tags and Submissions schema

server/database.sql, server/schema/contests/addModerator.js, server/schema/contests/index.js, server/schema/contests/removeModerator.js, server/schema/contests/updateContest.js, server/schema/submissions/createSubmission.js
=> fix: contests, submissions schemas and sql

server/models/contests/index.js, server/models/contests/updateQuestion.js, server/routes/contests/index.js, server/routes/contests/updateQuestion.js, server/routes/index.js, server/schema/contests/index.js, server/schema/contests/updateQuestion.js
**#60**
**API: update already added question.**
**`POST /contests/:contest_id/questions/:question_id/update`**
=> update question for contest

package-lock.json, package.json, server/index.js, server/jobs/deleteUnverifiedAccounts/deleteUnverifiedAccounts.js, server/jobs/deleteUnverifiedAccounts/index.js, server/jobs/index.js
=> Cron job to remove unverified accounts
